[package]
name = "drv-fpga-devices"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = { workspace = true }
cfg-if = { workspace = true }
drv-fpga-api = { path = "../../drv/fpga-api" }
drv-i2c-api = { path = "../../drv/i2c-api" }
drv-i2c-devices = { path = "../../drv/i2c-devices" }
drv-spi-api = { path = "../../drv/spi-api" }
drv-stm32xx-sys-api = { path = "../stm32xx-sys-api" }
gnarle = { path = "../../lib/gnarle" }
num-traits = { workspace = true }
ringbuf = { path = "../../lib/ringbuf" }
userlib = { path = "../../sys/userlib" }
zerocopy = { workspace = true }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false
