[package]
name = "drv-gimlet-seq-api"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
zerocopy.workspace = true

derive-idol-err = { path = "../../lib/derive-idol-err"  }
drv-gimlet-state = { path = "../gimlet-state" }
userlib = { path = "../../sys/userlib" }
ringbuf = { path = "../../lib/ringbuf" }

[build-dependencies]
idol.workspace = true

[lib]
test = false
doctest = false
bench = false
