name = "gimletlet-front-io"
board = "gimletlet-front-io"
inherit = "base-gimletlet2.toml"

[tasks.ecp5_front_io]
name = "drv-fpga-server"
features = ["front_io", "use-spi-core", "h753", "spi6"]
priority = 3
max-sizes = {flash = 32768, ram = 8192}
stacksize = 2048
start = true
uses = ["spi6"]
task-slots = ["sys", "i2c_driver"]
notifications = ["spi-irq"]
interrupts = {"spi6.irq" = "spi-irq"}

[tasks.vpd]
name = "task-vpd"
priority = 3
max-sizes = {flash = 8192, ram = 1024}
start = true
task-slots = ["sys", "i2c_driver"]
stacksize = 800

[config]

# SPI
[config.spi.spi6.devices.ecp5_front_io_fpga]
mux = "port_g"
cs = [{port = "G", pin = 10}] # FRONT_IO_CS_CONFIG_L

[config.spi.spi6.devices.ecp5_front_io_user_design]
mux = "port_g"
cs = [{port = "A", pin = 15}] # FRONT_IO_CS_USER_L

# The Front I/O board has a mux to select which FPGA the SPI bus will go to.
# The FPGA select pin is not exposed via TOML but is instead hardcoded as part
# of the fpga-server's main.rs. See the spi_mux_select parameter of the Driver
# instantiation.
# spi_mux_select = port B, pin 14 (wired out on J16)

# I2C
# Map "front_io0" to "i2c3"
# "front_io1" is not utilized currently so we ignore it for now

[[config.i2c.devices]]
bus = "i2c3"
address = 0b1010_000
device = "at24csw080"
description = "Front IO board FRUID"
removable = true

[[config.i2c.devices]]
bus = "i2c3"
address = 0b1110_011
device = "pca9538"
description = "Front IO GPIO expander"
removable = true

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0001_010
device = "pca9956b"
name = "front_leds_left"
description = "Front IO LED driver (left)"
removable = true
refdes = "U5"

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0001_011
device = "pca9956b"
name = "front_leds_right"
description = "Front IO LED driver (right)"
removable = true
refdes = "U6"

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_011
device = "tps546b24a"
description = "Front IO V3P3_SYS_A2 rail"
removable = true
power = {rails = ["V3P3_SYS_A2"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U7" # on front IO board

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_001
device = "tps546b24a"
description = "Front IO V3P3_QSFP0_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP0_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U15" # on front IO board

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_010
device = "tps546b24a"
description = "Front IO V3P3_QSFP1_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP1_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U18" # on front IO board
