name = "gimletlet-front-io"
board = "gimletlet-front-io"
inherit = "base-gimletlet2.toml"

[tasks.ecp5_front_io]
name = "drv-fpga-server"
features = ["front_io", "use-spi-core", "h753", "spi6"]
priority = 3
max-sizes = {flash = 32768, ram = 8192}
stacksize = 2048
start = true
uses = ["spi6"]
task-slots = ["sys", "i2c_driver"]
notifications = ["spi-irq"]
interrupts = {"spi6.irq" = "spi-irq"}

[tasks.auxflash]
name = "drv-auxflash-server"
priority = 3
max-sizes = {flash = 32768, ram = 4096}
features = ["h753"]
uses = ["quadspi"]
start = true
notifications = ["qspi-irq"]
interrupts = {"quadspi.irq" = "qspi-irq"}
stacksize = 3504
task-slots = ["sys"]

[tasks.sequencer]
name = "drv-gimletlet-front-io-seq-server"
priority = 4
stacksize = 4096
start = true
task-slots = [
    "sys",
    "i2c_driver",
    "auxflash",
    {front_io = "ecp5_front_io"}]
notifications = ["timer"]

[tasks.sensor]
name = "task-sensor"
features = []
priority = 4
stacksize = 1024
start = true
notifications = ["timer"]

[tasks.net]
name = "task-net"
stacksize = 6040
priority = 3
features = ["h753", "vlan", "gimletlet-nic", "use-spi-core", "spi4"]
max-sizes = {flash = 131072, ram = 65536, sram1 = 16384}
sections = {eth_bulk = "sram1"}
uses = ["eth", "tim16", "spi4"]
start = true
task-slots = ["sys", "jefe"]
notifications = ["eth-irq", "mdio-timer-irq", "spi-irq", "wake-timer"]

[tasks.net.interrupts]
"eth.irq" = "eth-irq"
"tim16.irq" = "mdio-timer-irq"
"spi4.irq" = "spi-irq"

[tasks.transceivers]
name = "drv-transceivers-server"
features = ["vlan"]
priority = 7
max-sizes = {flash = 65536, ram = 16384}
stacksize = 4096
start = true
task-slots = [
    "i2c_driver",
    "net",
    "sensor",
    "sys",
    {front_io = "ecp5_front_io"},
    {seq = "sequencer"}]
notifications = ["socket", "timer"]

[tasks.packrat]
name = "task-packrat"
priority = 3
max-sizes = {flash = 8192, ram = 2048}
start = true
# task-slots is explicitly empty: packrat should not send IPCs!
task-slots = []

[tasks.udpbroadcast]
name = "task-udpbroadcast"
priority = 6
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net", "packrat"]
features = ["vlan"]
notifications = ["socket"]

[tasks.udpecho]
name = "task-udpecho"
priority = 4
max-sizes = {flash = 16384, ram = 8192}
stacksize = 4096
start = true
task-slots = ["net"]
features = ["vlan"]
notifications = ["socket"]

[config]

# SPI
[config.spi.spi6.devices.ecp5_front_io_fpga]
mux = "port_g"
cs = [{port = "B", pin = 15}] # FRONT_IO_CS_CONFIG_L

[config.spi.spi6.devices.ecp5_front_io_user_design]
mux = "port_g"
cs = [{port = "D", pin = 8}] # FRONT_IO_CS_USER_L

# The Front I/O board has a mux to select which FPGA the SPI bus will go to.
# The FPGA select pin is not exposed via TOML but is instead hardcoded as part
# of the fpga-server's main.rs. See the spi_mux_select parameter of the Driver
# instantiation.
# spi_mux_select = port B, pin 14 (wired out on J16)

# I2C
# Map "front_io0" to "i2c3"
# "front_io1" is not utilized currently so we ignore it for now

[[config.i2c.devices]]
bus = "i2c3"
address = 0b1010_000
device = "at24csw080_front_io"
description = "Front IO board FRUID"
removable = true

[[config.i2c.devices]]
bus = "i2c3"
address = 0b1110_011
device = "pca9538"
description = "Front IO GPIO expander"
removable = true

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0001_010
device = "pca9956b"
name = "front_leds_left"
description = "Front IO LED driver (left)"
removable = true
refdes = "U5"

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0001_011
device = "pca9956b"
name = "front_leds_right"
description = "Front IO LED driver (right)"
removable = true
refdes = "U6"

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_011
device = "tps546b24a"
description = "Front IO V3P3_SYS_A2 rail"
removable = true
power = {rails = ["V3P3_SYS_A2"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U7" # on front IO board

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_001
device = "tps546b24a"
description = "Front IO V3P3_QSFP0_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP0_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U15" # on front IO board

[[config.i2c.devices]]
bus = "i2c3"
address = 0b0011_010
device = "tps546b24a"
description = "Front IO V3P3_QSFP1_A0 rail"
removable = true
power = {rails = ["V3P3_QSFP1_A0"] }
sensors = { temperature = 1, voltage = 1, current = 1 }
refdes = "J61_U18" # on front IO board

# Requires a spimux board to be installed at J2
# XXX - add notes about jumper configuration once that is figured out
[config.auxflash]
memory-size = 33_554_432 # 256 Mib / 32 MiB
slot-count = 16 # 2 MiB slots

[[auxflash.blobs]]
file = "drv/sidecar-front-io/sidecar_qsfp_x32_controller_rev_b_c.bit"
compress = true
tag = "QSFP"

[config.net]
vlan = { start = 0x301, count = 2 }
# UDP ports in sockets below are assigned in oxidecomputer/oana

[config.net.sockets.broadcast]
kind = "udp"
owner = {name = "udpbroadcast", notification = "socket"}
port = 997
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.echo]
kind = "udp"
owner = {name = "udpecho", notification = "socket"}
port = 7
tx = { packets = 3, bytes = 1024 }
rx = { packets = 3, bytes = 1024 }

[config.net.sockets.transceivers]
kind = "udp"
owner = {name = "transceivers", notification = "socket"}
port = 11112
tx = { packets = 3, bytes = 2048 }
rx = { packets = 3, bytes = 2048 }

#
# QSFP Module Temperature Sensors
#
[[config.sensor.devices]]
name = "xcvr0"
device = "qsfp"
description = "QSFP transceiver 0"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr1"
device = "qsfp"
description = "QSFP transceiver 1"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr2"
device = "qsfp"
description = "QSFP transceiver 2"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr3"
device = "qsfp"
description = "QSFP transceiver 3"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr4"
device = "qsfp"
description = "QSFP transceiver 4"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr5"
device = "qsfp"
description = "QSFP transceiver 5"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr6"
device = "qsfp"
description = "QSFP transceiver 6"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr7"
device = "qsfp"
description = "QSFP transceiver 7"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr8"
device = "qsfp"
description = "QSFP transceiver 8"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr9"
device = "qsfp"
description = "QSFP transceiver 9"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr10"
device = "qsfp"
description = "QSFP transceiver 10"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr11"
device = "qsfp"
description = "QSFP transceiver 11"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr12"
device = "qsfp"
description = "QSFP transceiver 12"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr13"
device = "qsfp"
description = "QSFP transceiver 13"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr14"
device = "qsfp"
description = "QSFP transceiver 14"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr15"
device = "qsfp"
description = "QSFP transceiver 15"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr16"
device = "qsfp"
description = "QSFP transceiver 16"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr17"
device = "qsfp"
description = "QSFP transceiver 17"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr18"
device = "qsfp"
description = "QSFP transceiver 18"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr19"
device = "qsfp"
description = "QSFP transceiver 19"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr20"
device = "qsfp"
description = "QSFP transceiver 20"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr21"
device = "qsfp"
description = "QSFP transceiver 21"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr22"
device = "qsfp"
description = "QSFP transceiver 22"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr23"
device = "qsfp"
description = "QSFP transceiver 23"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr24"
device = "qsfp"
description = "QSFP transceiver 24"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr25"
device = "qsfp"
description = "QSFP transceiver 25"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr26"
device = "qsfp"
description = "QSFP transceiver 26"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr27"
device = "qsfp"
description = "QSFP transceiver 27"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr28"
device = "qsfp"
description = "QSFP transceiver 28"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr29"
device = "qsfp"
description = "QSFP transceiver 29"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr30"
device = "qsfp"
description = "QSFP transceiver 30"
sensors.temperature = 1

[[config.sensor.devices]]
name = "xcvr31"
device = "qsfp"
description = "QSFP transceiver 31"
sensors.temperature = 1
