[package]
name = "drv-gimlet-state"
version = "0.1.0"
edition = "2021"

[dependencies]
userlib = { path = "../../sys/userlib" }
zerocopy = { workspace = true }
num-traits = { workspace = true }
ringbuf = { path = "../../lib/ringbuf" }

[lib]
test = false
doctest = false
bench = false
