[package]
name = "task-jeffrey"
version = "0.1.0"
edition = "2021"

[dependencies]
idol-runtime = { workspace = true }
hubpack = { workspace = true }
humpty = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }

dumptruck = { path = "../../lib/dumptruck" }
counters = { path = "../../lib/counters" }
ringbuf = { path = "../../lib/ringbuf" }
task-jefe-api = { path = "../../task/jefe-api" }
userlib = { path = "../../sys/userlib", features = ["panic-messages"] }

[features]

[build-dependencies]
idol = { workspace = true }
build-util = { path = "../../build/util" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "task-jeffrey"
test = false
doctest = false
bench = false
