[package]
name = "drv-hash-api"
version = "0.1.0"
edition = "2021"

[features]
default = ["counters"]

[dependencies]
idol-runtime.workspace = true
num-traits.workspace = true
zerocopy.workspace = true

counters = { path = "../../lib/counters", optional = true }
derive-idol-err = { path = "../../lib/derive-idol-err" }
userlib = { path = "../../sys/userlib" }

[build-dependencies]
idol.workspace = true

[lib]
test = false
doctest = false
bench = false
