[package]
name = "dump-types"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { workspace = true }
num-derive = { workspace = true }
humpty = { workspace = true }

counters = { path = "../../lib/counters" }
derive-idol-err = { path = "../../lib/derive-idol-err" }
dump-agent-api = { path = "../dump-agent-api" }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[lib]
test = false
doctest = false
bench = false
