name: release
on:
  workflow_call:

jobs:
  do-build:
    uses: ./.github/workflows/build-mfg.yml
    with:
       os: oxide-colo-builder-base

  release-build:
    needs: do-build
    runs-on: ubuntu-latest
    steps:
    - name: grab binary
      id: grab
      uses: actions/download-artifact@v4
      with:
        path: out
    - name: grab hubedit 
      uses: actions/checkout@v4
      with:
        path: hubtools
        repository: oxidecomputer/hubtools
    - name: build hubedit
      run: |
        cd hubtools
        cargo build
    - name: prep
      run: |
        OUT=${{ steps.grab.outputs.download-path }}
        for build in `ls $OUT`; do
           for f in `ls $OUT/$build`; do
              hubtools/target/debug/hubedit -a $OUT/$build/$f write-caboose --version 0.0.0-mfg
           done
        done

    - name: cut release
      uses: softprops/action-gh-release@v1
      with:
        name: "mfg release"
        fail_on_unmatched_files: true
        files: |
          ${{ steps.grab.outputs.download-path }}/*.zip
